# Generated by Django 3.1.14 on 2022-09-23 14:59

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220922_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-published_at',), 'verbose_name_plural': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=blog.models.upload_image),
        ),
    ]
